# Generated by Django 5.0.6 on 2024-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MEN', "Men's"), ('WOMEN', 'Womens')], help_text='Choose the category type: Men or Women', max_length=10, unique=True),
        ),
    ]
